In [1]:
import pandas as pd
import yfinance as yf

In [2]:
reliance = yf.download(
    "RELIANCE.NS",
    period="2y"
)

reliance.head()

$RELIANCE.NS: possibly delisted; no price data found  (period=2y)
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['RELIANCE.NS']: possibly delisted; no price data found  (period=2y)

Empty DataFrame
Columns: [(Adj Close, RELIANCE.NS), (Close, RELIANCE.NS), (High, RELIANCE.NS), (Low, RELIANCE.NS), (Open, RELIANCE.NS), (Volume, RELIANCE.NS)]
Index: []

In [3]:
tcs = yf.download(
    "TCS.NS",
    period="2y"
)

tcs.head()

$TCS.NS: possibly delisted; no price data found  (period=2y)
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['TCS.NS']: possibly delisted; no price data found  (period=2y)

Empty DataFrame
Columns: [(Adj Close, TCS.NS), (Close, TCS.NS), (High, TCS.NS), (Low, TCS.NS), (Open, TCS.NS), (Volume, TCS.NS)]
Index: []

In [4]:
infy = yf.download(
    "INFY.NS",
    period="2y"
)

infy.head()

$INFY.NS: possibly delisted; no price data found  (period=2y)
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['INFY.NS']: possibly delisted; no price data found  (period=2y)

Empty DataFrame
Columns: [(Adj Close, INFY.NS), (Close, INFY.NS), (High, INFY.NS), (Low, INFY.NS), (Open, INFY.NS), (Volume, INFY.NS)]
Index: []

In [5]:
reliance["Stock"] = "RELIANCE"

tcs["Stock"] = "TCS"

infy["Stock"] = "INFY"

In [6]:
stocks = pd.concat([
    reliance,
    tcs,
    infy
])

In [7]:
stocks.head()

Empty DataFrame
Columns: [(Adj Close, RELIANCE.NS), (Close, RELIANCE.NS), (High, RELIANCE.NS), (Low, RELIANCE.NS), (Open, RELIANCE.NS), (Volume, RELIANCE.NS), (Stock, ), (Adj Close, TCS.NS), (Close, TCS.NS), (High, TCS.NS), (Low, TCS.NS), (Open, TCS.NS), (Volume, TCS.NS), (Adj Close, INFY.NS), (Close, INFY.NS), (High, INFY.NS), (Low, INFY.NS), (Open, INFY.NS), (Volume, INFY.NS)]
Index: []

In [8]:
stocks.tail()

Empty DataFrame
Columns: [(Adj Close, RELIANCE.NS), (Close, RELIANCE.NS), (High, RELIANCE.NS), (Low, RELIANCE.NS), (Open, RELIANCE.NS), (Volume, RELIANCE.NS), (Stock, ), (Adj Close, TCS.NS), (Close, TCS.NS), (High, TCS.NS), (Low, TCS.NS), (Open, TCS.NS), (Volume, TCS.NS), (Adj Close, INFY.NS), (Close, INFY.NS), (High, INFY.NS), (Low, INFY.NS), (Open, INFY.NS), (Volume, INFY.NS)]
Index: []

In [9]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 0 entries
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   (Adj Close, RELIANCE.NS)  0 non-null      float64
 1   (Close, RELIANCE.NS)      0 non-null      float64
 2   (High, RELIANCE.NS)       0 non-null      float64
 3   (Low, RELIANCE.NS)        0 non-null      float64
 4   (Open, RELIANCE.NS)       0 non-null      float64
 5   (Volume, RELIANCE.NS)     0 non-null      float64
 6   (Stock, )                 0 non-null      object
 7   (Adj Close, TCS.NS)       0 non-null      float64
 8   (Close, TCS.NS)           0 non-null      float64
 9   (High, TCS.NS)            0 non-null      float64
 10  (Low, TCS.NS)             0 non-null      float64
 11  (Open, TCS.NS)            0 non-null      float64
 12  (Volume, TCS.NS)          0 non-null      float64
 13  (Adj Close, INFY.NS)      0 non-null      float64
 14  (Close, INFY.NS)          0 non-null      float64
 15  (High, INFY.NS)           0 non-null      float64
 16  (Low, INFY.NS)            0 non-null      float64
 17  (Open, INFY.NS)           0 non-null      float64
 18  (Volume, INFY.NS)         0 non-null      float64
dtypes: float64(18), object(1)
memory usage: 0.0+ bytes

In [10]:
stocks.describe()

Price,Adj Close,Close,High,Low,Open,Volume,Adj Close,Close,High,Low,Open,Volume,Adj Close,Close,High,Low,Open,Volume
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
stocks.isna().sum()

Price      Ticker
Adj Close  RELIANCE.NS    0
Close      RELIANCE.NS    0
High       RELIANCE.NS    0
Low        RELIANCE.NS    0
Open       RELIANCE.NS    0
Volume     RELIANCE.NS    0
Stock                     0
Adj Close  TCS.NS         0
Close      TCS.NS         0
High       TCS.NS         0
Low        TCS.NS         0
Open       TCS.NS         0
Volume     TCS.NS         0
Adj Close  INFY.NS        0
Close      INFY.NS        0
High       INFY.NS        0
Low        INFY.NS        0
Open       INFY.NS        0
Volume     INFY.NS        0
dtype: int64

In [12]:
stocks.shape

(0, 19)

In [13]:
stocks.to_csv(
    "data/stocks_raw.csv"
)