In [28]:
import pandas as pd
import yfinance as yf

In [29]:
reliance = yf.download("RELIANCE.NS", period="2y")
reliance["Stock"] = "RELIANCE"

tcs = yf.download("TCS.NS", period="2y")
tcs["Stock"] = "TCS"

infy = yf.download("INFY.NS", period="2y")
infy["Stock"] = "INFY"

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [30]:
reliance.reset_index(inplace=True)
tcs.reset_index(inplace=True)
infy.reset_index(inplace=True)

In [31]:
df = pd.concat([reliance, tcs, infy])

df.head()

Price,Date,Close,High,Low,Open,Volume,Stock,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS
0,2024-06-05,1403.821045,1414.097148,1367.607724,1405.056151,17464890.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-06-06,1414.541626,1426.497423,1404.413761,1417.901137,17855722.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-06-07,1452.434570,1454.460192,1409.502353,1411.478521,18558696.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-06-10,1453.867432,1475.555836,1450.581979,1452.434637,9251760.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-06-11,1439.317871,1456.115306,1437.341702,1451.495963,11774902.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1494 entries, 0 to 497
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Date, )               1494 non-null   datetime64[ns]
 1   (Close, RELIANCE.NS)   498 non-null    float64
 2   (High, RELIANCE.NS)    498 non-null    float64
 3   (Low, RELIANCE.NS)     498 non-null    float64
 4   (Open, RELIANCE.NS)    498 non-null    float64
 5   (Volume, RELIANCE.NS)  498 non-null    float64
 6   (Stock, )              1494 non-null   object
 7   (Close, TCS.NS)        498 non-null    float64
 8   (High, TCS.NS)         498 non-null    float64
 9   (Low, TCS.NS)          498 non-null    float64
 10  (Open, TCS.NS)         498 non-null    float64
 11  (Volume, TCS.NS)       498 non-null    float64
 12  (Close, INFY.NS)       498 non-null    float64
 13  (High, INFY.NS)        498 non-null    float64
 14  (Low, INFY.NS)         498 non-null    float64
 15  (Open, INFY.NS)        498 non-null    float64
 16  (Volume, INFY.NS)      498 non-null    float64
dtypes: datetime64[ns](1), float64(15), object(1)
memory usage: 210.1+ KB

In [33]:
df.describe()

Price,Date,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS
count,1494,498.000000,498.000000,498.000000,498.000000,4.980000e+02,498.000000,498.000000,498.000000,498.000000,4.980000e+02,498.000000,498.000000,498.000000,498.000000,4.980000e+02
mean,2025-06-04 15:13:44.096385536,1386.703703,1399.146488,1375.295247,1387.351187,1.318701e+07,3309.641806,3342.504341,3281.917244,3313.176686,2.920665e+06,1574.932563,1590.892922,1559.384718,1575.311023,8.497561e+06
min,2024-06-05 00:00:00,1151.951782,1161.221768,1105.304640,1122.506065,0.000000e+00,2201.899902,2234.699683,2176.883515,2221.873423,0.000000e+00,1095.000000,1121.900024,1089.000000,1102.000000,0.000000e+00
25%,2024-12-04 00:00:00,1314.281494,1330.720416,1304.219816,1317.955652,8.596812e+06,2955.953125,2975.761477,2933.401568,2954.257004,1.826542e+06,1451.579193,1464.053493,1437.457885,1453.940948,5.013321e+06
50%,2025-06-05 12:00:00,1394.940857,1408.860046,1383.154821,1394.552201,1.133943e+07,3281.714478,3304.588588,3257.079226,3283.306111,2.543334e+06,1560.705994,1579.660440,1546.382215,1561.511603,7.262263e+06
75%,2025-12-04 00:00:00,1459.998322,1473.163694,1448.933682,1462.118600,1.646413e+07,3841.842651,3881.236214,3806.438308,3843.592523,3.399176e+06,1770.867249,1792.080865,1753.906817,1771.733961,1.004126e+07
max,2026-06-05 00:00:00,1584.971802,1604.382010,1570.936597,1585.668486,4.263425e+07,4253.906250,4289.871200,4214.905946,4274.691846,1.633158e+07,1942.221191,1948.777171,1920.756459,1938.093361,6.908543e+07
std,NaN,101.251985,101.381146,101.509316,101.602753,6.763797e+06,546.984837,550.794384,542.436253,545.290421,1.839284e+06,202.575967,203.372414,201.168990,202.617545,5.974973e+06

In [34]:
df.isna().sum()

Price   Ticker
Date                     0
Close   RELIANCE.NS    996
High    RELIANCE.NS    996
Low     RELIANCE.NS    996
Open    RELIANCE.NS    996
Volume  RELIANCE.NS    996
Stock                    0
Close   TCS.NS         996
High    TCS.NS         996
Low     TCS.NS         996
Open    TCS.NS         996
Volume  TCS.NS         996
Close   INFY.NS        996
High    INFY.NS        996
Low     INFY.NS        996
Open    INFY.NS        996
Volume  INFY.NS        996
dtype: int64

In [35]:
df.to_csv("data/stocks_raw.csv", index=False)

In [36]:
print(df.columns)

MultiIndex([(  'Date',            ''),
            ( 'Close', 'RELIANCE.NS'),
            (  'High', 'RELIANCE.NS'),
            (   'Low', 'RELIANCE.NS'),
            (  'Open', 'RELIANCE.NS'),
            ('Volume', 'RELIANCE.NS'),
            ( 'Stock',            ''),
            ( 'Close',      'TCS.NS'),
            (  'High',      'TCS.NS'),
            (   'Low',      'TCS.NS'),
            (  'Open',      'TCS.NS'),
            ('Volume',      'TCS.NS'),
            ( 'Close',     'INFY.NS'),
            (  'High',     'INFY.NS'),
            (   'Low',     'INFY.NS'),
            (  'Open',     'INFY.NS'),
            ('Volume',     'INFY.NS')],
           names=['Price', 'Ticker'])