In [52]:
import pandas as pd

In [53]:
df = pd.read_csv("stocks_raw.csv")

In [54]:
df.head()

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2
0,NaN,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,NaN,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS,INFY.NS
1,2024-06-05,1403.821044921875,1414.097147783154,1367.6077240917773,1405.0561505394378,17464890.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-06-06,1414.5416259765625,1426.4974232883105,1404.4137607114592,1417.9011371144834,17855722.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-06-07,1452.4345703125,1454.4601915157414,1409.5023527154926,1411.478521453965,18558696.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-06-10,1453.867431640625,1475.5558362929214,1450.5819785928986,1452.4346368701142,9251760.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
print(df.columns.tolist())

['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Stock', 'Close.1', 'High.1', 'Low.1', 'Open.1', 'Volume.1', 'Close.2', 'High.2', 'Low.2', 'Open.2', 'Volume.2']

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495 entries, 0 to 1494
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1494 non-null   object
 1   Close     499 non-null    object
 2   High      499 non-null    object
 3   Low       499 non-null    object
 4   Open      499 non-null    object
 5   Volume    499 non-null    object
 6   Stock     1494 non-null   object
 7   Close.1   499 non-null    object
 8   High.1    499 non-null    object
 9   Low.1     499 non-null    object
 10  Open.1    499 non-null    object
 11  Volume.1  499 non-null    object
 12  Close.2   499 non-null    object
 13  High.2    499 non-null    object
 14  Low.2     499 non-null    object
 15  Open.2    499 non-null    object
 16  Volume.2  499 non-null    object
dtypes: object(17)
memory usage: 198.7+ KB

In [57]:
df["Close"] = pd.to_numeric(df["Close"], errors="coerce")

In [58]:
print(df["Close"].max())

1584.9718017578125

In [59]:
reliance = df[df["Stock"] == "RELIANCE"]

reliance.head()

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2
1,2024-06-05,1403.821045,1414.097147783154,1367.6077240917773,1405.0561505394378,17464890.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-06-06,1414.541626,1426.4974232883105,1404.4137607114592,1417.9011371144834,17855722.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-06-07,1452.434570,1454.4601915157414,1409.5023527154926,1411.478521453965,18558696.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-06-10,1453.867432,1475.5558362929214,1450.5819785928986,1452.4346368701142,9251760.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-06-11,1439.317871,1456.1153056542432,1437.3417023219272,1451.4959629037996,11774902.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
reliance_above_1500 = reliance[reliance["Close"] > 1500]

reliance_above_1500.head()

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2
16,2024-06-27,1512.312622,1519.1797603831344,1488.0551018777237,1495.7127559544517,28383030.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2024-06-28,1546.747437,1562.1615299634889,1512.782033239127,1512.782033239127,28957336.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2024-07-01,1541.559937,1560.5805616644209,1537.138282854078,1543.9066370278445,7724306.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2024-07-02,1546.525146,1554.7509013864856,1538.4475077589818,1550.7985635373939,7749246.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2024-07-03,1533.927002,1556.2329594590622,1524.391963189475,1547.661278880494,9049620.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
reliance["Pct_Change"] = reliance["Close"].pct_change() * 100

reliance.head()

C:\Users\Ms642\AppData\Local\Temp\ipykernel_20172\2773305123.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reliance["Pct_Change"] = reliance["Close"].pct_change() * 100

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2,Pct_Change
1,2024-06-05,1403.821045,1414.097147783154,1367.6077240917773,1405.0561505394378,17464890.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-06-06,1414.541626,1426.4974232883105,1404.4137607114592,1417.9011371144834,17855722.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.763671
3,2024-06-07,1452.434570,1454.4601915157414,1409.5023527154926,1411.478521453965,18558696.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.678814
4,2024-06-10,1453.867432,1475.5558362929214,1450.5819785928986,1452.4346368701142,9251760.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.098652
5,2024-06-11,1439.317871,1456.1153056542432,1437.3417023219272,1451.4959629037996,11774902.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000749

In [62]:
reliance["Abs_Change"] = reliance["Pct_Change"].abs()

reliance.head()

C:\Users\Ms642\AppData\Local\Temp\ipykernel_20172\1403941999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reliance["Abs_Change"] = reliance["Pct_Change"].abs()

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2,Pct_Change,Abs_Change
1,2024-06-05,1403.821045,1414.097147783154,1367.6077240917773,1405.0561505394378,17464890.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-06-06,1414.541626,1426.4974232883105,1404.4137607114592,1417.9011371144834,17855722.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.763671,0.763671
3,2024-06-07,1452.434570,1454.4601915157414,1409.5023527154926,1411.478521453965,18558696.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.678814,2.678814
4,2024-06-10,1453.867432,1475.5558362929214,1450.5819785928986,1452.4346368701142,9251760.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.098652,0.098652
5,2024-06-11,1439.317871,1456.1153056542432,1437.3417023219272,1451.4959629037996,11774902.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000749,1.000749

In [63]:
sorted_days = reliance.sort_values(
    by="Abs_Change",
    ascending=False
)

sorted_days.head(10)

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2,Pct_Change,Abs_Change
222,2025-04-28,1357.080322,1362.830589793996,1308.8963407951755,1328.5268607294433,31104496.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.259918,5.259918
451,2026-03-27,1341.895630,1398.235116023098,1338.809921280448,1394.552193095842,23266517.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.599813,4.599813
396,2026-01-06,1500.661499,1561.77894010158,1489.4135782872731,1561.77894010158,27417125.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.467398,4.467398
231,2025-05-12,1424.200684,1426.679278587822,1388.0131966802994,1388.0131966802994,10674081.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.305835,4.305835
15,2024-06-26,1495.984497,1500.875466568816,1427.905458276952,1428.8194845866847,22014882.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.117522,4.117522
83,2024-10-03,1394.928467,1436.9902726871705,1390.070396353704,1424.2750076222521,37757294.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.949272,3.949272
343,2025-10-20,1460.049316,1467.0170999313523,1426.7034952504036,1433.3726108781723,24721978.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.529072,3.529072
209,2025-04-04,1194.385254,1234.7863505024063,1182.9342181609516,1230.473619610667,17908652.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.523666,3.523666
32,2024-07-22,1482.793701,1519.1798633102128,1481.4103587992008,1518.9328421942273,19674376.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.502879,3.502879
42,2024-08-05,1430.079224,1466.2184833782828,1416.1719837774867,1462.3649300475706,17046704.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.468226,3.468226

In [64]:
top10 = reliance.nlargest(
    10,
    "Abs_Change"
)

top10

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2,Pct_Change,Abs_Change
222,2025-04-28,1357.080322,1362.830589793996,1308.8963407951755,1328.5268607294433,31104496.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.259918,5.259918
451,2026-03-27,1341.895630,1398.235116023098,1338.809921280448,1394.552193095842,23266517.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.599813,4.599813
396,2026-01-06,1500.661499,1561.77894010158,1489.4135782872731,1561.77894010158,27417125.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.467398,4.467398
231,2025-05-12,1424.200684,1426.679278587822,1388.0131966802994,1388.0131966802994,10674081.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.305835,4.305835
15,2024-06-26,1495.984497,1500.875466568816,1427.905458276952,1428.8194845866847,22014882.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.117522,4.117522
83,2024-10-03,1394.928467,1436.9902726871705,1390.070396353704,1424.2750076222521,37757294.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.949272,3.949272
343,2025-10-20,1460.049316,1467.0170999313523,1426.7034952504036,1433.3726108781723,24721978.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.529072,3.529072
209,2025-04-04,1194.385254,1234.7863505024063,1182.9342181609516,1230.473619610667,17908652.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.523666,3.523666
32,2024-07-22,1482.793701,1519.1798633102128,1481.4103587992008,1518.9328421942273,19674376.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.502879,3.502879
42,2024-08-05,1430.079224,1466.2184833782828,1416.1719837774867,1462.3649300475706,17046704.0,RELIANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.468226,3.468226

In [ ]:
tcs = df[df["Stock"] == "TCS"].copy()

tcs["Pct_Change"] = tcs["Close"].pct_change(fill_method=None) * 100

tcs["Abs_Change"] = tcs["Pct_Change"].abs()

tcs.nlargest(10, "Abs_Change")

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2,Pct_Change,Abs_Change
499,2024-06-05,NaN,NaN,NaN,NaN,NaN,TCS,3491.65380859375,3526.4637252968946,3448.3629196102897,3463.274759262659,2799670.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500,2024-06-06,NaN,NaN,NaN,NaN,NaN,TCS,3569.894287109375,3578.748191817024,3487.0404698598118,3523.8540736442465,4328036.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,2024-06-07,NaN,NaN,NaN,NaN,NaN,TCS,3629.1220703125,3648.74050345654,3576.324932841619,3576.324932841619,4552445.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502,2024-06-10,NaN,NaN,NaN,NaN,NaN,TCS,3596.26953125,3640.2594108529347,3580.6120547712317,3630.1008115349123,1734661.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
503,2024-06-11,NaN,NaN,NaN,NaN,NaN,TCS,3590.118896484375,3616.074682376751,3579.773716105295,3583.5016762366204,1419898.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,2024-06-12,NaN,NaN,NaN,NaN,NaN,TCS,3571.059326171875,3628.7029976160984,3567.145013751887,3610.901897932011,2177001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,2024-06-13,NaN,NaN,NaN,NaN,NaN,TCS,3614.396728515625,3625.4409004223003,3590.0252823719024,3594.498879632959,1932323.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,2024-06-14,NaN,NaN,NaN,NaN,NaN,TCS,3571.432373046875,3624.50915875349,3567.6577679887782,3624.50915875349,1860730.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
507,2024-06-18,NaN,NaN,NaN,NaN,NaN,TCS,3555.634765625,3580.705202970566,3536.94832258526,3565.840009543117,1774045.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508,2024-06-19,NaN,NaN,NaN,NaN,NaN,TCS,3543.146484375,3573.1101006391245,3534.991571536935,3567.331580370277,1509050.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
infy = df[df["Stock"] == "INFY"].copy()

infy["Pct_Change"] = infy["Close"].pct_change(fill_method=None) * 100

infy["Abs_Change"] = infy["Pct_Change"].abs()

infy.nlargest(10, "Abs_Change")

,Date,Close,High,Low,Open,Volume,Stock,Close.1,High.1,Low.1,Open.1,Volume.1,Close.2,High.2,Low.2,Open.2,Volume.2,Pct_Change,Abs_Change
997,2024-06-05,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1373.3564453125,1380.9430124283645,1344.594848794161,1344.594848794161,9233424.0,NaN,NaN
998,2024-06-06,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1413.833984375,1415.8026912541518,1380.4627967662166,1387.6171483700416,12660930.0,NaN,NaN
999,2024-06-07,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1472.749755859375,1478.607696455328,1418.6356360706318,1422.2368434730788,24075302.0,NaN,NaN
1000,2024-06-10,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1440.2427978515625,1469.1005184048513,1437.8900560410068,1464.7790697698574,6810606.0,NaN,NaN
1001,2024-06-11,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1436.4014892578125,1446.6768867495505,1434.67286293827,1440.530920339611,4853054.0,NaN,NaN
1002,2024-06-12,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1426.2701416015625,1448.8857708643502,1423.9173996680136,1447.205207418443,9564320.0,NaN,NaN
1003,2024-06-13,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1434.6728515625,1445.2844554182486,1430.2553942803347,1435.68123644537,7307565.0,NaN,NaN
1004,2024-06-14,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1429.8233642578125,1444.0360586769375,1427.0864701658527,1444.0360586769375,4237727.0,NaN,NaN
1005,2024-06-18,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1438.7542724609375,1447.2051523581276,1436.0654413858667,1437.6019330325926,5420939.0,NaN,NaN
1006,2024-06-19,NaN,NaN,NaN,NaN,NaN,INFY,NaN,NaN,NaN,NaN,NaN,1451.382568359375,1455.5119996711499,1437.3138282236787,1445.2845473689924,5493456.0,NaN,NaN

Reliance Data Filtering

Filtered RELIANCE stock data from dataset.

Daily Percentage Change

Calculated percentage change using pct_change().

Volatility Analysis

Sorted data using absolute percentage change.

Top 10 Volatile Days

Displayed the 10 most volatile trading days.